### ISSUE TITLE
Weekly runner has been erroring out for the past month

### ISSUE THREAD

**Issue by philmichel** [m0ngr31/genmon#1]
Hi there,

thank you so much for this docker container. It works very well!

I just wanted to point out that, if I am not mistaken, the weekly runner meant to build new images every week has been erroring out for the past month.

It seems like the github.rest.repos.createRelease(...) call is throwing an http error.

Just wanted to flag it in case you were unaware. Would be awesome to get this building regularly  again.

Thank you!

**Comment by philmichel** [comment]
This might be a permissions issue. Perhaps the workflow needs explicit read/write permissions?

**Comment by m0ngr31** [comment]
It seems like Github has changed something... I have another repo that works in a similar fashion and it just stopped working as well. I'll see what I can do to figure it out

**Comment by m0ngr31** [comment]
I figured out the issue(s)... There were 2:

1. The default permission for actions must have changed recently because the actions didn't have write permissions on the repo.
2. Since the scheduled action was using the default repo authentication key that Github provides, it wouldn't trigger the other one since it's using the same key. I had to create a PAT for the scheduled one and now it works.
